object Version {
  val APP           = "0.0.1-SNAPSHOT"
  val SCALA         = "2.11.7"
  val LOGBACK       = "1.1.2"
  val MYSQLCONN     = "5.1.36"
  val CUCUMBER      = "1.2.2"
  val DBUNIT        = "2.5.1"
  val JACKSON       = "2.6.1"
  val JACKSONMODULE = "2.6.1"
  val JUNIT         = "4.11"
  val GUICE         = "4.0"
  val JAXRS         = "3.0.9.Final"
  val JAVAEE        = "7.0"
  val HIBERNATE     = "5.1.0.Final"
  val H2            = "1.4.190"
  val SELENIUM      = "2.48.2"
  val PLAYMAILER    = "3.0.1"
  val JJWT          = "0.6.0"
  val HTTPCLIENT    = "4.5.1"
  val HTTPCORE      = "4.4.4"
  val COMMONS_IO    = "2.5"
}
