DELETE FROM user WHERE email = 'test.user@atos.net';

INSERT INTO PUBLIC.USER(EMAIL, FORENAME, SURNAME, PASSWORD, JOB_TITLE, BASE_SITE, PHONE, ACTIVATION_DATE, FAILED_LOGIN_COUNT, LAST_ACCESS, ROLE)
VALUES ('test.user@atos.net', 'Test', 'user', '$2a$10$epw62Yj2RATKQgmZurgEtON4GLCZrol4HV8mHENlZAyq9xfdksd3S', NULL, NULL, NULL, DATE '2016-10-11', 0, TIMESTAMP '2016-10-11 16:47:37.7', 'USER');